#! /usr/bin/env sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          30
bspc config top_padding         38

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  \#dcdfe4
bspc config active_border_color \#56b6c2
bspc config focused_border_color \#98c379

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
wal -i ~/Pictures/Mingle.png
picom&
make -C .config/polybar
dusnt &
eww daemon&
mpris-proxy &
